// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EdgeDB from "rescript-edgedb/src/EdgeDB.mjs";

var queryText = "# @name AddAccount\n      insert Account {\n        context_id := <str>$context_id,\n      }";

function query(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText, args);
}

function transaction(transaction$1, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$1, queryText, args);
}

var AddAccount = {
  queryText: queryText,
  query: query,
  transaction: transaction
};

var queryText$1 = "# @name RemoveAccount\n      delete Account\n      filter .id = <uuid>$id";

function query$1(client, args, onError) {
  return EdgeDB.QueryHelpers.single(client, queryText$1, args, onError);
}

function transaction$1(transaction$2, args, onError) {
  return EdgeDB.TransactionHelpers.single(transaction$2, queryText$1, args, onError);
}

var RemoveAccount = {
  queryText: queryText$1,
  query: query$1,
  transaction: transaction$1
};

export {
  AddAccount ,
  RemoveAccount ,
}
/* EdgeDB Not a pure module */
