// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EdgeDB from "rescript-edgedb/src/EdgeDB.mjs";

var queryText = "select Answer {\n      id,\n      answer_num_by_user,\n      user: {\n        context_id\n      }\n    } order by .answer_num_by_user;";

function query(client) {
  return EdgeDB.QueryHelpers.many(client, queryText, undefined);
}

function transaction(transaction$1) {
  return EdgeDB.TransactionHelpers.many(transaction$1, queryText, undefined);
}

var AllAnswers = {
  queryText: queryText,
  query: query,
  transaction: transaction
};

export {
  AllAnswers ,
}
/* EdgeDB Not a pure module */
