// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EdgeDB from "rescript-edgedb/src/EdgeDB.mjs";

var queryText = "# @name allAnswers\n      select Answer {\n        id,\n        answer_num_by_user,\n        user: {\n          context_id\n        }\n      } order by .answer_num_by_user;";

function query(client) {
  return EdgeDB.QueryHelpers.many(client, queryText, undefined);
}

function transaction(transaction$1) {
  return EdgeDB.TransactionHelpers.many(transaction$1, queryText, undefined);
}

var AllAnswers = {
  queryText: queryText,
  query: query,
  transaction: transaction
};

var queryText$1 = "# @name AddAnswer\n      insert Answer {\n          answer_num_by_user := <int16>$answer_num_by_user,\n          day := <str>$day,\n          user := (\n              select Account filter .context_id = <str>$context_id\n          ),\n          option := (\n              select Option filter .id = <uuid>$id\n          )\n      }";

function query$1(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText$1, args);
}

function transaction$1(transaction$2, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$2, queryText$1, args);
}

var AddAnswer = {
  queryText: queryText$1,
  query: query$1,
  transaction: transaction$1
};

export {
  AllAnswers ,
  AddAnswer ,
}
/* EdgeDB Not a pure module */
