// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EdgeDB from "rescript-edgedb/src/EdgeDB.mjs";

var queryText = "# @name AddQuestion\n      insert Question {\n        question := <str>$question\n      }";

function query(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText, args);
}

function transaction(transaction$1, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$1, queryText, args);
}

var AddQuestion = {
  queryText: queryText,
  query: query,
  transaction: transaction
};

var queryText$1 = "# @name RemoveQuestion\n      delete Question\n      filter .id = <uuid>$id";

function query$1(client, args, onError) {
  return EdgeDB.QueryHelpers.single(client, queryText$1, args, onError);
}

function transaction$1(transaction$2, args, onError) {
  return EdgeDB.TransactionHelpers.single(transaction$2, queryText$1, args, onError);
}

var RemoveQuestion = {
  queryText: queryText$1,
  query: query$1,
  transaction: transaction$1
};

export {
  AddQuestion ,
  RemoveQuestion ,
}
/* EdgeDB Not a pure module */
