// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EdgeDB from "rescript-edgedb/src/EdgeDB.mjs";

var queryText = "# @name AddFlashQueue\n    insert FlashQueue {\n      flash_queue_id := <QueueId>$flash_queue_id,\n      question := (\n        select Question filter .id = <uuid>$question_id\n      )\n    }";

function query(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText, args);
}

function transaction(transaction$1, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$1, queryText, args);
}

var AddFlashQueue = {
  queryText: queryText,
  query: query,
  transaction: transaction
};

var queryText$1 = "# @name RemoveFlashQueue\n    delete FlashQueue\n    filter .id = <uuid>$id";

function query$1(client, args, onError) {
  return EdgeDB.QueryHelpers.single(client, queryText$1, args, onError);
}

function transaction$1(transaction$2, args, onError) {
  return EdgeDB.TransactionHelpers.single(transaction$2, queryText$1, args, onError);
}

var RemoveFlashQueue = {
  queryText: queryText$1,
  query: query$1,
  transaction: transaction$1
};

var queryText$2 = "# @name AddQuestionQueue\n    insert QuestionQueue {\n      question_queue_id := <QueueId>$question_queue_id,\n      question := (\n        select Question filter .id = <uuid>$question_id\n      )\n    }";

function query$2(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText$2, args);
}

function transaction$2(transaction$3, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$3, queryText$2, args);
}

var AddQuestionQueue = {
  queryText: queryText$2,
  query: query$2,
  transaction: transaction$2
};

var queryText$3 = "# @name RemoveQuestionQueue\n    delete QuestionQueue\n    filter .id = <uuid>$id";

function query$3(client, args, onError) {
  return EdgeDB.QueryHelpers.single(client, queryText$3, args, onError);
}

function transaction$3(transaction$4, args, onError) {
  return EdgeDB.TransactionHelpers.single(transaction$4, queryText$3, args, onError);
}

var RemoveQuestionQueue = {
  queryText: queryText$3,
  query: query$3,
  transaction: transaction$3
};

var queryText$4 = "# @name AddCommunityQueue\n    insert CommunityQueue {\n      community_queue_id := <QueueId>$community_queue_id,\n      question := (\n        select Question filter .id = <uuid>$question_id\n      )\n    }";

function query$4(client, args) {
  return EdgeDB.QueryHelpers.singleRequired(client, queryText$4, args);
}

function transaction$4(transaction$5, args) {
  return EdgeDB.TransactionHelpers.singleRequired(transaction$5, queryText$4, args);
}

var AddCommunityQueue = {
  queryText: queryText$4,
  query: query$4,
  transaction: transaction$4
};

var queryText$5 = "# @name RemoveCommunityQueue\n    delete CommunityQueue\n    filter .id = <uuid>$id";

function query$5(client, args, onError) {
  return EdgeDB.QueryHelpers.single(client, queryText$5, args, onError);
}

function transaction$5(transaction$6, args, onError) {
  return EdgeDB.TransactionHelpers.single(transaction$6, queryText$5, args, onError);
}

var RemoveCommunityQueue = {
  queryText: queryText$5,
  query: query$5,
  transaction: transaction$5
};

export {
  AddFlashQueue ,
  RemoveFlashQueue ,
  AddQuestionQueue ,
  RemoveQuestionQueue ,
  AddCommunityQueue ,
  RemoveCommunityQueue ,
}
/* EdgeDB Not a pure module */
