// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Options__edgeql from "./__generated__/Options__edgeql.mjs";

var addOption = Options__edgeql.AddOptions.transaction;

var removeOption = Options__edgeql.RemoveOption.transaction;

var AddOptions;

var RemoveOption;

export {
  AddOptions ,
  addOption ,
  RemoveOption ,
  removeOption ,
}
/* Options__edgeql Not a pure module */
