name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run bundled CLI
        run: ./dist/Cli.js --help

      - name: Setup EdgeDB
        uses: edgedb/setup-edgedb@v1
        with:
          instance-name: "dbTestProject"

      - name: Init EdgDB
        working-directory: ./dbTestProject
        run: edgedb project init --non-interactive

      - name: Setup and build DB test project
        working-directory: ./dbTestProject
        run: npm ci && npm run build:rescript && npm run build:edgedb

      - name: Run DB tests
        working-directory: ./dbTestProject
        run: npm test
