// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Accounts__edgeql from "./__generated__/Accounts__edgeql.mjs";

var addAccount = Accounts__edgeql.AddAccount.transaction;

var removeAccount = Accounts__edgeql.RemoveAccount.transaction;

var AddAccount;

var RemoveAccount;

export {
  AddAccount ,
  addAccount ,
  RemoveAccount ,
  removeAccount ,
}
/* Accounts__edgeql Not a pure module */
