// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Answers__edgeql from "./__generated__/Answers__edgeql.mjs";

function allAnswers(client) {
  var query = Answers__edgeql.AllAnswers.query;
  return query(client);
}

var addAnswer = Answers__edgeql.AddAnswer.transaction;

var removeAnswer = Answers__edgeql.RemoveAnswer.transaction;

var AddAnswer;

var RemoveAnswer;

export {
  allAnswers ,
  AddAnswer ,
  addAnswer ,
  RemoveAnswer ,
  removeAnswer ,
}
/* Answers__edgeql Not a pure module */
