// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Questions__edgeql from "./__generated__/Questions__edgeql.mjs";

var addQuestion = Questions__edgeql.AddQuestion.transaction;

var removeQuestion = Questions__edgeql.RemoveQuestion.transaction;

var AddQuestion;

var RemoveQuestion;

export {
  AddQuestion ,
  addQuestion ,
  RemoveQuestion ,
  removeQuestion ,
}
/* Questions__edgeql Not a pure module */
